### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by jeongm** [jeongm/Algorithms#3]
1. Finding pairs of duplicate elements 
  - 5c19067
2. Given a number, find two numbers that add up to given number
  - a06327b

**Comment by jeongm** [comment]
Initializing arrays : ```memset(a,1,sizeof(a));```

**Comment by MoonHyuk** [comment]
memset은 값을 바이트 단위로 넣기 때문에 0또는 -1이 아닌 값을 넣으면 의도하지 않은 결과가 나올 수 있습니다.
int형 배열을 `memset(a, 1, sizeof(a)); ` 로 초기화 하면 제 로컬에서는 16843009가 들어가네요.
배열을 0또는 -1로 초기화 할때만 memset을 써야하고 다른 값으로 초기화 하고 싶으면 `std::fill_n` 를 써야 합니다.

**Comment by jeongm** [comment]
Dynamic Programming: 
- overlapping subproblem
- optimal substructure

한 번 계산한 값이 또 사용되면 그 값을 저장해서 다음에 그 값이 필요할 때 연산하지 않고 바로 호출해서 사용한다.
-> memoization

Top-Down 
제일 큰 문제를 제일 작은 문제로 쪼개서 연산
recursion

Bottom-Up
제일 작은 문제부터 제일 큰 문제까지
for 


d 에 무엇이 들어가야 하는가?

**Comment by jeongm** [comment]
- Print Doubles
`cout << setprecision(3) << fixed << result << '%' << '\n';`

`fixed` declares how many setprecision digits below decimal point

**Comment by jeongm** [comment]
- How to handle tricky inputs
  - Accept until new line
```
        string temp;
        getline(cin, temp);
        istringstream iss(temp);
        while (iss >> a)    coefficients.push_back(a);
```
     
    - `cin.ignore()` to avoid `getline()` approaching wrong line
